function renderPortfolio(container){
    const d=AppData;
    container.innerHTML=`
    <div class="page-header"><h1>Project Portfolio</h1><button class="btn btn-primary" onclick="addProject()"><i class="fas fa-plus"></i> Add Project</button></div>
    <div class="table-container"><table><thead><tr><th>Code</th><th>Name</th><th>Client</th><th>Location</th><th>Manager</th><th>Contract Value</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    ${d.projects.map(p=>`<tr><td><strong>${p.code}</strong></td><td>${p.name}</td><td>${p.client}</td><td>${p.location}</td><td>${p.manager}</td><td>${formatCurrency(p.contractValue)}</td><td>${getStatusBadge(p.status)}</td><td><button class="btn btn-sm" onclick="editProject('${p.id}')"><i class="fas fa-edit"></i></button></td></tr>`).join('')}
    </tbody></table></div>
    <div style="margin-top:12px;padding:12px;background:#f0f9ff;border-radius:8px;font-size:13px"><strong>Total Contract Value:</strong> ${formatCurrency(d.projects.reduce((s,p)=>s+p.contractValue,0))}</div>`;
}
function addProject(){
    const cOpts=AppData.clients.map(c=>`<option value="${c.name}">${c.name}</option>`).join('');
    openModal('Add Project',`<form id="proj-form"><div class="form-grid"><div class="form-group"><label>Code</label><input name="code" required placeholder="e.g. NH48"></div><div class="form-group"><label>Name</label><input name="name" required></div><div class="form-group"><label>Client</label><select name="client">${cOpts}</select></div><div class="form-group"><label>Location</label><input name="location"></div><div class="form-group"><label>Manager</label><input name="manager"></div><div class="form-group"><label>Contract Value (₹)</label><input type="number" name="contractValue" required></div><div class="form-group"><label>Start Date</label><input type="date" name="startDate"></div><div class="form-group"><label>End Date</label><input type="date" name="endDate"></div><div class="form-group"><label>Status</label><select name="status"><option>Ongoing</option><option>Planning</option><option>On Hold</option><option>Complete</option></select></div></div></form>`,`<button class="btn btn-primary" onclick="saveProject()">Save</button>`);
}
function saveProject(){const f=document.getElementById('proj-form'),fd=new FormData(f);AppData.projects.push({id:generateId('PRJ'),code:fd.get('code'),name:fd.get('name'),client:fd.get('client'),location:fd.get('location'),manager:fd.get('manager'),contractValue:Number(fd.get('contractValue')),status:fd.get('status'),startDate:fd.get('startDate'),endDate:fd.get('endDate')});saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Project added');}
function editProject(id){const p=AppData.projects.find(x=>x.id===id);if(!p)return;const cOpts=AppData.clients.map(c=>`<option value="${c.name}" ${c.name===p.client?'selected':''}>${c.name}</option>`).join('');openModal('Edit Project',`<form id="proj-form"><div class="form-grid"><div class="form-group"><label>Code</label><input name="code" value="${p.code}" required></div><div class="form-group"><label>Name</label><input name="name" value="${p.name}" required></div><div class="form-group"><label>Client</label><select name="client">${cOpts}</select></div><div class="form-group"><label>Location</label><input name="location" value="${p.location||''}"></div><div class="form-group"><label>Manager</label><input name="manager" value="${p.manager||''}"></div><div class="form-group"><label>Contract Value (₹)</label><input type="number" name="contractValue" value="${p.contractValue}" required></div><div class="form-group"><label>Status</label><select name="status"><option ${p.status==='Ongoing'?'selected':''}>Ongoing</option><option ${p.status==='Planning'?'selected':''}>Planning</option><option ${p.status==='On Hold'?'selected':''}>On Hold</option><option ${p.status==='Complete'?'selected':''}>Complete</option></select></div></div></form>`,`<button class="btn btn-primary" onclick="updateProject('${id}')">Update</button>`);
}
function updateProject(id){const p=AppData.projects.find(x=>x.id===id);if(!p)return;const fd=new FormData(document.getElementById('proj-form'));p.code=fd.get('code');p.name=fd.get('name');p.client=fd.get('client');p.location=fd.get('location');p.manager=fd.get('manager');p.contractValue=Number(fd.get('contractValue'));p.status=fd.get('status');saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Project updated');}

function renderClients(container){
    const d=AppData;
    container.innerHTML=`
    <div class="page-header"><h1>Clients</h1><button class="btn btn-primary" onclick="addClient()"><i class="fas fa-plus"></i> Add Client</button></div>
    <div class="table-container"><table><thead><tr><th>Name</th><th>Contact Person</th><th>Phone</th><th>Email</th><th>Projects</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    ${d.clients.map(c=>`<tr><td><strong>${c.name}</strong></td><td>${c.contactPerson}</td><td>${c.phone}</td><td>${c.email}</td><td>${c.projects}</td><td>${getStatusBadge(c.status)}</td><td><button class="btn btn-sm" onclick="editClient('${c.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteClient('${c.id}')"><i class="fas fa-trash"></i></button></td></tr>`).join('')}
    </tbody></table></div>`;
}
function addClient(){openModal('Add Client',`<form id="client-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" required></div><div class="form-group"><label>Contact Person</label><input name="contactPerson"></div><div class="form-group"><label>Phone</label><input name="phone"></div><div class="form-group"><label>Email</label><input name="email"></div><div class="form-group"><label>Address</label><input name="address"></div></div></form>`,`<button class="btn btn-primary" onclick="saveClient()">Save</button>`);}
function saveClient(){const fd=new FormData(document.getElementById('client-form'));AppData.clients.push({id:generateId('CLT'),name:fd.get('name'),contactPerson:fd.get('contactPerson'),phone:fd.get('phone'),email:fd.get('email'),address:fd.get('address'),projects:0,status:'Active'});saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Client added');}
function editClient(id){const c=AppData.clients.find(x=>x.id===id);if(!c)return;openModal('Edit Client',`<form id="client-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" value="${c.name}" required></div><div class="form-group"><label>Contact Person</label><input name="contactPerson" value="${c.contactPerson||''}"></div><div class="form-group"><label>Phone</label><input name="phone" value="${c.phone||''}"></div><div class="form-group"><label>Email</label><input name="email" value="${c.email||''}"></div><div class="form-group"><label>Address</label><input name="address" value="${c.address||''}"></div></div></form>`,`<button class="btn btn-primary" onclick="updateClient('${id}')">Update</button>`);}
function updateClient(id){const c=AppData.clients.find(x=>x.id===id);if(!c)return;const fd=new FormData(document.getElementById('client-form'));c.name=fd.get('name');c.contactPerson=fd.get('contactPerson');c.phone=fd.get('phone');c.email=fd.get('email');c.address=fd.get('address');saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Client updated');}
function deleteClient(id){showConfirm('Delete Client','Are you sure?',r=>{if(r){AppData.clients=AppData.clients.filter(c=>c.id!==id);saveData(AppData);handleRoute();toast('Client deleted');}});}

function renderSites(container){
    const d=AppData;
    container.innerHTML=`
    <div class="page-header"><h1>Sites</h1><button class="btn btn-primary" onclick="addSite()"><i class="fas fa-plus"></i> Add Site</button></div>
    <div class="table-container"><table><thead><tr><th>Name</th><th>Project</th><th>Location</th><th>Lat</th><th>Lng</th><th>Geofence (m)</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    ${d.sites.map(s=>`<tr><td><strong>${s.name}</strong></td><td>${s.project}</td><td>${s.location||'-'}</td><td>${s.lat}</td><td>${s.lng}</td><td>${s.geofenceRadius}</td><td>${getStatusBadge(s.status)}</td><td><button class="btn btn-sm" onclick="editSite('${s.id}')"><i class="fas fa-edit"></i></button></td></tr>`).join('')}
    </tbody></table></div>`;
}
function addSite(){const pOpts=AppData.projects.map(p=>`<option value="${p.name}">${p.name}</option>`).join('');openModal('Add Site',`<form id="site-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" required></div><div class="form-group"><label>Project</label><select name="project">${pOpts}</select></div><div class="form-group"><label>Location</label><input name="location"></div><div class="form-group"><label>Latitude</label><input type="number" name="lat" step="0.0001" required></div><div class="form-group"><label>Longitude</label><input type="number" name="lng" step="0.0001" required></div><div class="form-group"><label>Geofence Radius (m)</label><input type="number" name="geofenceRadius" value="500" required></div></div></form>`,`<button class="btn btn-primary" onclick="saveSite()">Save</button>`);}
function saveSite(){const fd=new FormData(document.getElementById('site-form'));AppData.sites.push({id:generateId('SITE'),name:fd.get('name'),project:fd.get('project'),location:fd.get('location'),lat:Number(fd.get('lat')),lng:Number(fd.get('lng')),geofenceRadius:Number(fd.get('geofenceRadius')),status:'Active'});saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Site added');}
function editSite(id){const s=AppData.sites.find(x=>x.id===id);if(!s)return;const pOpts=AppData.projects.map(p=>`<option value="${p.name}" ${p.name===s.project?'selected':''}>${p.name}</option>`).join('');openModal('Edit Site',`<form id="site-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" value="${s.name}" required></div><div class="form-group"><label>Project</label><select name="project">${pOpts}</select></div><div class="form-group"><label>Location</label><input name="location" value="${s.location||''}"></div><div class="form-group"><label>Latitude</label><input type="number" name="lat" step="0.0001" value="${s.lat}" required></div><div class="form-group"><label>Longitude</label><input type="number" name="lng" step="0.0001" value="${s.lng}" required></div><div class="form-group"><label>Geofence Radius (m)</label><input type="number" name="geofenceRadius" value="${s.geofenceRadius}" required></div></div></form>`,`<button class="btn btn-primary" onclick="updateSite('${id}')">Update</button>`);}
function updateSite(id){const s=AppData.sites.find(x=>x.id===id);if(!s)return;const fd=new FormData(document.getElementById('site-form'));s.name=fd.get('name');s.project=fd.get('project');s.location=fd.get('location');s.lat=Number(fd.get('lat'));s.lng=Number(fd.get('lng'));s.geofenceRadius=Number(fd.get('geofenceRadius'));saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Site updated');}
