function renderCompanies(container){
    const d=AppData;
    container.innerHTML=`
    <div class="page-header"><h1>Companies</h1><button class="btn btn-primary" onclick="addCompany()"><i class="fas fa-plus"></i> Add Company</button></div>
    <div class="table-container"><table><thead><tr><th>Short Code</th><th>Name</th><th>GSTIN</th><th>PAN</th><th>PF Code</th><th>ESIC Code</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    ${d.companies.map(c=>`<tr><td><strong>${c.shortCode}</strong></td><td>${c.name}</td><td style="font-size:11px">${c.gstin}</td><td>${c.pan}</td><td>${c.pfCode}</td><td>${c.esicCode}</td><td>${getStatusBadge(c.status)}</td><td><button class="btn btn-sm" onclick="editCompany('${c.id}')"><i class="fas fa-edit"></i></button></td></tr>`).join('')}
    </tbody></table></div>`;
}
function addCompany(){openModal('Add Company',`<form id="company-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" required></div><div class="form-group"><label>Short Code</label><input name="shortCode" required></div><div class="form-group"><label>Address</label><input name="address"></div><div class="form-group"><label>GSTIN</label><input name="gstin"></div><div class="form-group"><label>PAN</label><input name="pan"></div><div class="form-group"><label>PF Code</label><input name="pfCode"></div><div class="form-group"><label>ESIC Code</label><input name="esicCode"></div></div></form>`,`<button class="btn btn-primary" onclick="saveCompany()">Save</button>`);}
function saveCompany(){const fd=new FormData(document.getElementById('company-form'));AppData.companies.push({id:generateId('COMP'),name:fd.get('name'),shortCode:fd.get('shortCode'),address:fd.get('address'),gstin:fd.get('gstin'),pan:fd.get('pan'),pfCode:fd.get('pfCode'),esicCode:fd.get('esicCode'),status:'Active'});saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Company added');}
function editCompany(id){const c=AppData.companies.find(x=>x.id===id);if(!c)return;openModal('Edit Company',`<form id="company-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" value="${c.name}" required></div><div class="form-group"><label>Short Code</label><input name="shortCode" value="${c.shortCode}" required></div><div class="form-group"><label>Address</label><input name="address" value="${c.address||''}"></div><div class="form-group"><label>GSTIN</label><input name="gstin" value="${c.gstin||''}"></div><div class="form-group"><label>PAN</label><input name="pan" value="${c.pan||''}"></div><div class="form-group"><label>PF Code</label><input name="pfCode" value="${c.pfCode||''}"></div><div class="form-group"><label>ESIC Code</label><input name="esicCode" value="${c.esicCode||''}"></div></div></form>`,`<button class="btn btn-primary" onclick="updateCompany('${id}')">Update</button>`);}
function updateCompany(id){const c=AppData.companies.find(x=>x.id===id);if(!c)return;const fd=new FormData(document.getElementById('company-form'));c.name=fd.get('name');c.shortCode=fd.get('shortCode');c.address=fd.get('address');c.gstin=fd.get('gstin');c.pan=fd.get('pan');c.pfCode=fd.get('pfCode');c.esicCode=fd.get('esicCode');saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Company updated');}

function renderSettingsUsers(container){
    const d=AppData;
    container.innerHTML=`
    <div class="page-header"><h1>User Management</h1><button class="btn btn-primary" onclick="addUser()"><i class="fas fa-plus"></i> Add User</button></div>
    <div class="table-container"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>
    ${d.users.map(u=>`<tr><td><strong>${u.name}</strong></td><td>${u.email}</td><td><span class="badge-status badge-blue">${u.role}</span></td><td>${getStatusBadge(u.status)}</td><td>${u.lastLogin}</td><td><button class="btn btn-sm" onclick="editUser('${u.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteUser('${u.id}')"><i class="fas fa-trash"></i></button></td></tr>`).join('')}
    </tbody></table></div>`;
}
function addUser(){
    const rOpts=AppData.roles.map(r=>`<option value="${r.name}">${r.name}</option>`).join('');
    openModal('Add User',`<form id="user-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" required></div><div class="form-group"><label>Email</label><input type="email" name="email" required></div><div class="form-group"><label>Role</label><select name="role">${rOpts}</select></div><div class="form-group"><label>Status</label><select name="status"><option>Active</option><option>Inactive</option></select></div></div></form>`,`<button class="btn btn-primary" onclick="saveUser()">Save</button>`);
}
function saveUser(){const fd=new FormData(document.getElementById('user-form'));AppData.users.push({id:generateId('USR'),name:fd.get('name'),email:fd.get('email'),role:fd.get('role'),status:fd.get('status'),lastLogin:'-'});saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('User added');}
function editUser(id){const u=AppData.users.find(x=>x.id===id);if(!u)return;const rOpts=AppData.roles.map(r=>`<option value="${r.name}" ${r.name===u.role?'selected':''}>${r.name}</option>`).join('');openModal('Edit User',`<form id="user-form"><div class="form-grid"><div class="form-group"><label>Name</label><input name="name" value="${u.name}" required></div><div class="form-group"><label>Email</label><input type="email" name="email" value="${u.email}" required></div><div class="form-group"><label>Role</label><select name="role">${rOpts}</select></div><div class="form-group"><label>Status</label><select name="status"><option ${u.status==='Active'?'selected':''}>Active</option><option ${u.status==='Inactive'?'selected':''}>Inactive</option></select></div></div></form>`,`<button class="btn btn-primary" onclick="updateUser('${id}')">Update</button>`);}
function updateUser(id){const u=AppData.users.find(x=>x.id===id);if(!u)return;const fd=new FormData(document.getElementById('user-form'));u.name=fd.get('name');u.email=fd.get('email');u.role=fd.get('role');u.status=fd.get('status');saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('User updated');}
function deleteUser(id){showConfirm('Delete User','Are you sure you want to delete this user?',r=>{if(r){AppData.users=AppData.users.filter(u=>u.id!==id);saveData(AppData);handleRoute();toast('User deleted');}});}

function renderSettingsRoles(container){
    const d=AppData;
    container.innerHTML=`
    <div class="page-header"><h1>Roles & Permissions</h1><button class="btn btn-primary" onclick="addRole()"><i class="fas fa-plus"></i> Add Role</button></div>
    <div class="table-container"><table><thead><tr><th>Role Name</th><th>Permissions</th><th>Users</th><th>Actions</th></tr></thead><tbody>
    ${d.roles.map(r=>`<tr><td><strong>${r.name}</strong></td><td style="font-size:12px">${r.permissions.map(p=>`<span class="badge-status badge-gray" style="margin:2px">${p}</span>`).join(' ')}</td><td>${r.users}</td><td><button class="btn btn-sm" onclick="editRole('${r.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteRole('${r.id}')"><i class="fas fa-trash"></i></button></td></tr>`).join('')}
    </tbody></table></div>`;
}
function addRole(){openModal('Add Role',`<form id="role-form"><div class="form-grid"><div class="form-group"><label>Role Name</label><input name="name" required></div><div class="form-group full-width"><label>Permissions (comma-separated)</label><input name="permissions" placeholder="Dashboard, Employees, Attendance..." required></div></div></form>`,`<button class="btn btn-primary" onclick="saveRole()">Save</button>`);}
function saveRole(){const fd=new FormData(document.getElementById('role-form'));AppData.roles.push({id:generateId('ROLE'),name:fd.get('name'),permissions:fd.get('permissions').split(',').map(p=>p.trim()),users:0});saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Role added');}
function editRole(id){const r=AppData.roles.find(x=>x.id===id);if(!r)return;openModal('Edit Role',`<form id="role-form"><div class="form-grid"><div class="form-group"><label>Role Name</label><input name="name" value="${r.name}" required></div><div class="form-group full-width"><label>Permissions (comma-separated)</label><input name="permissions" value="${r.permissions.join(', ')}" required></div></div></form>`,`<button class="btn btn-primary" onclick="updateRole('${id}')">Update</button>`);}
function updateRole(id){const r=AppData.roles.find(x=>x.id===id);if(!r)return;const fd=new FormData(document.getElementById('role-form'));r.name=fd.get('name');r.permissions=fd.get('permissions').split(',').map(p=>p.trim());saveData(AppData);closeModal({target:document.getElementById('modal-overlay')});handleRoute();toast('Role updated');}
function deleteRole(id){showConfirm('Delete Role','Are you sure you want to delete this role?',r=>{if(r){AppData.roles=AppData.roles.filter(x=>x.id!==id);saveData(AppData);handleRoute();toast('Role deleted');}});}
